name: Deploy application
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v5
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test code  
      - name: Build code
        run : npm run build
      - name: Deploy code
        run: echo "Deploying..."
   
